sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Ge6mtVkPe+LetPgULYxCGOj3vHZybCg2bydsVpOcxa37JVlyWXwUt2c1DULVmhCEFckKBuhIoHLiGxwLWCQszZjtFDZyGyJ4+IQkpKaubczniZ64RYmxkqyYu9e82hQDqvPJ0drgvD30OSoUoMgU7uvDI/u3acoxsGY7PwLMz6jDOMD8tcf2oNeLdnFdi8kcQsySsb4uTTUtdkoC/gcvKt/85YHtwnJ2FPZ5D19KMrfRXBwJKy7uT4USZHTLTDxc6ANj8+EMQJ4FGlcMz/zOtYeR8MDMrAtnGG42KljmWX37AAWJP2p8jEY2K3bZFq3O1o4BPiyy4th/mnZ4onQZ3mnvBaaX1uO76kKtBJE3FK6MY4+r2eyHvCkaOJExrwAraa978IdPig7+S4iONstIKnas1k4UQq/2H9RBRjM2zKR5hgYewZ0fS8VtgsbyQWbmgCqYHpgeSIRFn8maj3Jgeun6JxwZpvcqg6m3yZsn4SIv5bpe0xNgwu0TD4+aZGWbQagkG8p178jihh5XpAs1lOEqvWV/hWHE+WVwrs/s1ifc0KNSlJiCHKfxRHc6GsQgePBlgGhUXmn32U5lboNLS8JDkgi0wuwpiCPpr/YOML41fFQv3LuTPslVhNMqWeS9YAup81vGsIHUq//Ql1T1z0FJz/W85roXXpdWOo32B5E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Her-Weight-in-Gold_5896
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy